### ISSUE TITLE
Content outside the boxes

### ISSUE THREAD

**Issue by misuto** [SpaceLenore/gitlab-darkdash#1]
Summary
----

The issue list can be outside of the "box" if this particular resolution is used.  

The screens resolution is `1280x1024` and the Chrome v70.0 is used, refer to the screenshot below.

![screenshot_20181103_072123](https://user-images.githubusercontent.com/3165211/47948865-37f91200-df39-11e8-86fd-8602a2623295.png)

**Comment by SpaceLenore** [comment]
Thanks for the bug report! This issue have now been fixed. :trumpet:
